{
 "title": "Raspberry PI",
 "description": "VPS used for nginx and wireguard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.42.4:9100\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"192.168.42.4:9100\"} - node_memory_MemAvailable_bytes{instance=\"192.168.42.4:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.42.4:9100\",mode=\"idle\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{device=\"/dev/mmcblk0p2\",fstype=\"ext4\",instance=\"192.168.42.4:9100\",job=\"node_exporter\",mountpoint=\"/\"} / node_filesystem_free_bytes{device=\"/dev/mmcblk0p2\",fstype=\"ext4\",instance=\"192.168.42.4:9100\",job=\"node_exporter\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=\"192.168.42.4:9100\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets{instance=\"192.168.42.4:9100\"}[5m])"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"192.168.42.4:9100\"}[5m])"
    }
   ]
  }
 ]
}